name: quiz_assistant_env
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - tk
  - pip:
      - mss
      - pytesseract
      - opencv-python
      - pillow
      - google-generativeai
      - numpy
